mod distillation;
mod promotion;
mod prompt;
mod proposal;
mod retrieval;
mod rollout;

pub use distillation::EpiphanyDistillInput;
pub use distillation::EpiphanyDistillProposal;
pub use distillation::distill_observation;
pub use promotion::EpiphanyPromotionDecision;
pub use promotion::EpiphanyPromotionInput;
pub use promotion::evaluate_promotion;
pub use prompt::render_epiphany_state;
pub use proposal::EpiphanyMapProposal;
pub use proposal::EpiphanyMapProposalInput;
pub use proposal::propose_map_update;
pub use retrieval::EPIPHANY_RETRIEVAL_DEFAULT_LIMIT;
pub use retrieval::EPIPHANY_RETRIEVAL_MAX_LIMIT;
pub use retrieval::EpiphanyRetrieveQuery;
pub use retrieval::EpiphanyRetrieveResponse;
pub use retrieval::EpiphanyRetrieveResult;
pub use retrieval::EpiphanyRetrieveResultKind;
pub use retrieval::index_workspace;
pub use retrieval::retrieval_state_for_workspace;
pub use retrieval::retrieve_workspace;
pub use rollout::latest_epiphany_state_from_rollout_items;
